language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-serial
      - python-yaml
      - wkhtmltopdf
      - libgeos-dev
      - postgis
      - postgresql-9.2-postgis-scripts
      - postgresql-9.2-postgis-2.3
      - postgresql-9.3-postgis-scripts
      - postgresql-9.3-postgis-2.4

services:
  - postgresql

before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='info@jarsa.com.mx'
  - secure: "yjlRq8y9By4/+gxbNBSgVH6GtGE292/e9IxjBpzZ95DHxD6+QbxJJhH3vriZk7fIqoZggkpSQOurPwv0NA5ozA0DsdyP8kXyFoPB2oBgL14jkI6hrJbFtOwQzDnSqzj1CfZ4exIYy/TGq4zh4s4i4qpnnYjKSPJcNnapAyVk1Gi80L9DLL71+BUN4Q9F0wCmzklTiSAbi9alHLLpeoON//F+Y6N7KZID0G89CJJaOx+Yu/yN38oM3aaN1ImIWH5cExDxc2Yf62H9q2Xiua16tfh+fr+Q/V/Wb7v6SDLNhAqFzHFEz95aK9Sp9id6DgX/j0Dh1kZtBA1RxQT8TVzK2k5PcCOK1Cshd5raHDltgBUn7Zq6Jn73gl+shMdfIoZXPWBoNeYwvzFDN6rxHaBSzhpmvEe8w4/GnF0D7olroDaFNvSSJu8+c1IyB7K9h6iGr7kC4ZQrvtUFGoufL4iC0u37jZQBeRJ1y8R8KV7iH0OcWIGJWOcR7LV3PNL5Fh88fe7vI8KflspJM/c2FJkXFb9gpg4o4T02bHj+eLKgcZLBXk15cVa9RY9BGhYYu86aTBLADxQLbmiA5/nJjMAOg92tt+1cxPHjqDCxxAhp1VpCp49qlbPTHi6ZsD4NZw+tCYueYptY3830rP87CVRQPjXZ+3XncsGFILXpdfbI3Fc="
  - TRANSIFEX_PROJECT_SLUG='Jarsa-vehicle-maintenance-system-9-0'
  - TRANSIFEX_ORGANIZATION='jarsa'
  - TRANSIFEX_TEAM='62171'

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/Jarsa/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - if [[ "${OCA_RUNBOT}" == "1" ]]; then git clone --depth=1 git@github.com:odoo/enterprise.git -b $VERSION ${HOME}/enterprise; fi
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
